coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 40%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        # advanced
        branches:
          - master
          - develop
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no